---
- set_fact:
    cluster_hostname: "{{ cluster_hostname | default(groups['masters'][0]) }}"
    cluster_port: "{{ cluster_port | default('6443') }}"

- set_fact:
    config_path: "{{ config_path | default(lookup('env','HOME')+'/.ktrw') }}"
  delegate_to: 127.0.0.1

- set_fact:
    cluster_name: "{{ cluster_hostname.split('.')[0] | default('kubernetes') }}"

- set_fact:
    cluster_config_path: "{{ config_path }}/{{ cluster_name }}"

- name: Download kube-proxy
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v1.11.2/bin/linux/amd64/kube-proxy
    dest: /usr/local/bin/kube-proxy
    mode: 0755
    owner: root
    group: root

- name: Ensure directories exist
  file:
    state: directory
    path: "/etc/kubernetes/{{ item }}"
    mode: 0755
  with_items:
    - pki
    - config

- name: Create kube-proxy kubeconfig
  command: "kubectl config set-cluster kubernetes --certificate-authority {{ cluster_config_path }}/pki/master/ca.pem --embed-certs=true --server=https://{{ cluster_hostname }}:{{ cluster_port }} --kubeconfig {{ cluster_config_path }}/kube-proxy.kubeconfig"
  delegate_to: 127.0.0.1
  run_once: True

- name: set-credentials 
  command: "kubectl config set-credentials system:kube-proxy --client-certificate {{ cluster_config_path }}/pki/master/kube-proxy.pem --client-key {{ cluster_config_path }}/pki/master/kube-proxy-key.pem --embed-certs=true --kubeconfig {{ cluster_config_path }}/kube-proxy.kubeconfig"
  delegate_to: 127.0.0.1
  run_once: True
 
- name: set-context
  command: "kubectl config set-context default --cluster=kubernetes --user=system:kube-proxy --kubeconfig {{ cluster_config_path }}/kube-proxy.kubeconfig"
  delegate_to: 127.0.0.1
  run_once: True
 
- name: use-context
  command: "kubectl config use-context default --kubeconfig {{ cluster_config_path }}/kube-proxy.kubeconfig"
  delegate_to: 127.0.0.1
  run_once: True

- name: Change file permission for kubeconfig
  file:
    path: "{{ cluster_config_path }}/kube-proxy.kubeconfig"
    mode: 0644
  delegate_to: 127.0.0.1

- name: Copy kubeconfig
  copy:
    src: "{{ cluster_config_path }}/kube-proxy.kubeconfig"
    dest: /etc/kubernetes/config/kube-proxy.kubeconfig

- name: Copy kube-proxy config
  copy:
    src: kube-proxy.yml
    dest: /etc/kubernetes/config/

- name: Create systemd unit file
  template:
    src: kube-proxy.service.j2
    dest: /etc/systemd/system/kube-proxy.service

- name: daemon-reload
  systemd: 
    daemon_reload: True

- name: Start and enable kube-proxy
  systemd:
    name: kube-proxy
    state: restarted
    enabled: True