---
- set_fact:
    cluster_hostname: "{{ cluster_hostname | default(groups['masters'][0]) }}"
    cluster_cidr: "{{ cluster_cidr | default('10.19.0.0/16') }}"

- name: Ensure directories exist
  file:
    state: directory
    path: "{{ item }}"
    mode: 0755
  with_items:
    - /etc/cni/net.d
    - /opt/cni/bin

- name: Download cni
  unarchive:
    src: https://github.com/containernetworking/plugins/releases/download/v0.6.0/cni-plugins-amd64-v0.6.0.tgz
    dest: /opt/cni/bin/
    remote_src: True

- name: Create loopback net
  template:
    src: 99-loopback.conf.j2
    dest: /etc/cni/net.d/99-loopback.conf


