---
- name: Ensure directories exist
  file:
    state: directory
    path: "{{ item }}"
    mode: 0755
  with_items:
    - /etc/cni/net.d
    - /opt/cni/bin

- name: Download cni
  unarchive:
    src: https://github.com/containernetworking/plugins/releases/download/v0.6.0/cni-plugins-amd64-v0.6.0.tgz
    dest: /opt/cni/bin/
    remote_src: True

- name: Create networks
  template:
    src: "{{ item }}"
    dest: "/etc/cni/net.d/{{ item[:-3]}}"
  with_items:
    - 10-bridge.conflist.j2
    - 99-loopback.conf.j2


