---
- hosts: nodes
  tasks:

  - name: Stop any running containers
    shell: "for container in $(runc --root /run/containerd/runc/k8s.io/ list | awk '{print $1}' | grep -v ID); do runc --root /run/containerd/runc/k8s.io/ kill $container; done"
    ignore_errors: True

  - name: Delete all containers
    shell: "for container in $(runc --root /run/containerd/runc/k8s.io/ list | awk '{print $1}' | grep -v ID); do runc --root /run/containerd/runc/k8s.io/ delete $container; done"
    ignore_errors: True

  - stat:
      path: /etc/systemd/system/containerd.service
    register: result

  - name: Stop containerd
    systemd:
      name: containerd
      state: stopped
      enabled: False
    when: result.stat.exists

  - name: Remove unit file
    file:
      path: /etc/systemd/system/containerd.service
      state: absent

  - stat:
      path: /etc/systemd/system/kubelet.service
    register: result
  
  - name: Stop kubelet
    systemd:
      name: kubelet
      state: stopped
      enabled: False
    when: result.stat.exists

  - name: Remove unit file
    file:
      path: /etc/systemd/system/kubelet.service
      state: absent

  - stat:
      path: /etc/systemd/system/kube-proxy.service
    register: result
  
  - name: Stop kube-proxy
    systemd:
      name: kube-proxy
      state: stopped
      enabled: False
    when: result.stat.exists

  - name: Remove unit file
    file:
      path: /etc/systemd/system/kube-proxy.service
      state: absent

  - name: Find mounted directories
    shell: "awk '$2 ~ path {print $2}' path=/var/lib/kubelet /proc/mounts"
    register: "result"

  - name: Unmount volumes
    mount:
      path: "{{ item }}"
      state: unmounted
    with_items:
      - "{{ result.stdout_lines }}"

  - name: Remove directories
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /var/lib/kubelet
      - /var/lib/containerd
      - /var/lib/cni
      - /etc/kubernetes
      - /etc/containerd
      - /etc/cni
      - /opt/cni

  - name: Remove binaries
    file:
      path: "/usr/local/bin/{{ item }}"
      state: absent
    with_items:
      - ctr
      - containerd
      - containerd-shim
      - containerd-shim-runc-v1
      - containerd-release
      - containerd-stress
      - runc
      - kubelet
      - kube-proxy

- hosts: etcd
  tasks:
  - stat:
      path: /etc/systemd/system/etcd.service
    register: result

  - name: Stop etcd
    systemd:
      name: etcd
      state: stopped
      enabled: False
    when: result.stat.exists

  - name: Remove unit file
    file:
      path: /etc/systemd/system/etcd.service
      state: absent

  - name: Remove etcd directories
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /var/lib/etcd
      - /etc/etcd

  - name: Remove binaries
    file:
      path: "/usr/local/bin/{{ item }}"
      state: absent
    with_items:
      - etcd
      - etcdctl

- hosts: masters
  tasks:
  - stat: 
      path: "/etc/systemd/system/kube-controller-manager.service"
    register: result

  - name: Stop kube-controller-manager service
    systemd:
      name: kube-controller-manager
      state: stopped
      enabled: False
    when: result.stat.exists

  - stat: 
      path: "/etc/systemd/system/kube-scheduler.service"
    register: result

  - name: Stop kube-scheduler service
    systemd:
      name: kube-scheduler
      state: stopped
      enabled: False
    when: result.stat.exists

  - stat: 
      path: "/etc/systemd/system/kube-apiserver.service"
    register: result

  - name: Stop kube-apiserver service
    systemd:
      name: kube-apiserver
      state: stopped
      enabled: False
    when: result.stat.exists

  - name: Remove directories
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /etc/kubernetes

  - name: Remove binaries
    file:
      path: "/usr/local/bin/{{ item }}"
      state: absent
    with_items:
      - kube-apiserver
      - kube-controller-manager
      - kube-scheduler

  - name: Remove systemd unit files
    file:
      path: "/etc/systemd/system/{{ item }}.service"
      state: absent
    with_items:
      - kube-apiserver
      - kube-controller-manager
      - kube-scheduler