- hosts: nodes
  tasks:

  - name: Stop any running containers
    shell: "for container in $(runc --root /run/containerd/runc/k8s.io/ list | awk '{print $1}' | grep -v ID); do runc --root /run/containerd/runc/k8s.io/ kill $container; done"
    ignore_errors: True

  - name: Delete all containers
    shell: "for container in $(runc --root /run/containerd/runc/k8s.io/ list | awk '{print $1}' | grep -v ID); do runc --root /run/containerd/runc/k8s.io/ delete $container; done"
    ignore_errors: True

  - stat:
      path: /etc/systemd/system/containerd.service
    register: result

  - name: Stop containerd
    systemd:
      name: containerd
      state: stopped
      enabled: False
    when: result.stat.exists

  - name: Remove unit file
    file:
      path: /etc/systemd/system/containerd.service
      state: absent

  - stat:
      path: /etc/systemd/system/kubelet.service
    register: result
  
  - name: Stop kubelet
    systemd:
      name: kubelet
      state: stopped
      enabled: False
    when: result.stat.exists

  - name: Remove unit file
    file:
      path: /etc/systemd/system/kubelet.service
      state: absent

  - stat:
      path: /etc/systemd/system/kube-proxy.service
    register: result
  
  - name: Stop kube-proxy
    systemd:
      name: kube-proxy
      state: stopped
      enabled: False
    when: result.stat.exists

  - name: Remove unit file
    file:
      path: /etc/systemd/system/kube-proxy.service
      state: absent

  - name: Remove directories
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /var/lib/kubelet
      - /etc/kubernetes
      - /etc/containerd
      - /etc/cni
      - /opt/cni

  - name: Remove binaries
    file:
      path: "/usr/local/bin/{{ item }}"
      state: absent
    with_items:
      - ctr
      - containerd
      - containerd-shim
      - containerd-release
      - containerd-stress
      - runc
      - kubelet

- hosts: etcd
  tasks:
  - stat:
      path: /etc/systemd/system/etcd.service
    register: result

  - name: Stop etcd
    systemd:
      name: etcd
      state: stopped
      enabled: False
    when: result.stat.exists

  - name: Remove unit file
    file:
      path: /etc/systemd/system/etcd.service
      state: absent

  - name: Remove etcd directories
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /var/lib/etcd
      - /etc/etcd

  - name: Remove binaries
    file:
      path: "/usr/local/bin/{{ item }}"
      state: absent
    with_items:
      - etcd
      - etcdctl

- hosts: masters
  tasks:
  - stat: 
      path: "/etc/systemd/system/kube-controller-manager.service"
    register: result

  - name: Stop kube-controller-manager service
    systemd:
      name: kube-controller-manager
      state: stopped
      enabled: False
    when: result.stat.exists

  - stat: 
      path: "/etc/systemd/system/kube-scheduler.service"
    register: result

  - name: Stop kube-scheduler service
    systemd:
      name: kube-scheduler
      state: stopped
      enabled: False
    when: result.stat.exists

  - stat: 
      path: "/etc/systemd/system/kube-apiserver.service"
    register: result

  - name: Stop kube-apiserver service
    systemd:
      name: kube-apiserver
      state: stopped
      enabled: False
    when: result.stat.exists

  - name: Remove directories
    file:
      path: "{( item }}"
      state: absent
    with_items:
      - /etc/kubernetes

  - name: Remove binaries
    file:
      path: "/usr/local/bin/{{ item }}"
      state: absent
    with_items:
      - kube-apiserver
      - kube-controller-manager
      - kube-scheduler

# - hosts: 127.0.0.1
#   connection: local
#   tasks:
#   - name: Remove tmp cert dir
#     file:
#       path: ~/.kube-tmp/
#       state: absent