- hosts: localhost
  connection: local
  roles:
  - certificates

- hosts: etcd
  roles:
  - etcd

- hosts: masters
  roles:
  - kube-apiserver
  - kube-controller-manager
  - kube-scheduler

- hosts: nodes
  roles:
  - cni
  - containerd
  - runc
  - kube-proxy
  - kubelet

- hosts: etcd
  serial: 1
  handlers:
  - include: roles/etcd/handlers/main.yml