- hosts: localhost
  connection: local
  roles:
    - kubectl
    - certificates

- hosts: etcd
  roles:
    - etcd

- hosts: masters
  roles:
    - kubectl
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler

- hosts: nodes
  roles:
    - kubectl
    - cni
    - containerd
    - runc
    - kube-proxy
    - kubelet