- hosts: localhost
  connection: local
  roles:
  - certificates

- hosts: etcd
  vars:
    skip_etcd_handlers: True
  roles:
  - etcd

- hosts: masters
  roles:
  - kube-apiserver
  - kube-controller-manager
  - kube-scheduler

- hosts: nodes
  roles:
  - cni
  - containerd
  - runc
  - kube-proxy
  - kubelet

- hosts: etcd,masters
  serial: 1
  vars:
    skip_etcd_handlers: False
  tasks:
  - import_tasks: roles/etcd/handlers/main.yml