- name: Determine IP address of one master
  shell: "dig {{ groups['nodes'][0] }} +short"
  register: result
  failed_when: (result.rc != 0 or result.stdout == "") and cluster_ip is undefined
  delegate_to: 127.0.0.1

- set_fact:
    cluster_ip: "{{ cluster_ip | default(result.stdout) }}"
    cluster_hostname: "{{ cluster_hostname | default(groups['nodes'][0]) }}"
    cluster_port: "{{ cluster_port | default('6443') }}"

- name: Download kubelet
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v1.11.2/bin/linux/amd64/kubelet
    dest: /usr/local/bin/kubelet
    mode: 0755
    owner: root
    group: root

- name: Ensure directories exist
  file:
    state: directory
    path: "/etc/kubernetes/{{ item }}"
    mode: 0755
  with_items:
    - pki
    - config

- name: Copy certificates
  copy:
    src: "{{ item }}"
    dest: /etc/kubernetes/pki
  with_fileglob:
    - "~/.kube-tmp/pki/node/system:node:{{ ansible_fqdn }}*"
    - "~/.kube-tmp/pki/master/ca.pem"

- name: Create kubelet kubeconfig
  command: "kubectl config set-cluster kubernetes --certificate-authority ~/.kube-tmp/pki/master/ca.pem --embed-certs=true --server=https://{{ cluster_hostname }}:{{ cluster_port }} --kubeconfig ~/.kube-tmp/system:node:{{ ansible_fqdn }}.kubeconfig"
  delegate_to: 127.0.0.1

- name: set-credentials 
  command: "kubectl config set-credentials system:node:{{ ansible_hostname }} --client-certificate ~/.kube-tmp/pki/node/system:node:{{ ansible_fqdn }}.pem --client-key ~/.kube-tmp/pki/node/system:node:{{ ansible_fqdn }}-key.pem --embed-certs=true --kubeconfig ~/.kube-tmp/system:node:{{ ansible_fqdn }}.kubeconfig"
  delegate_to: 127.0.0.1
 
- name: set-context
  command: "kubectl config set-context default --cluster=kubernetes --user=system:node:{{ ansible_hostname }} --kubeconfig ~/.kube-tmp/system:node:{{ ansible_fqdn }}.kubeconfig"
  delegate_to: 127.0.0.1
 
- name: use-context
  command: "kubectl config use-context default --kubeconfig ~/.kube-tmp/system:node:{{ ansible_fqdn }}.kubeconfig"
  delegate_to: 127.0.0.1

- name: Copy kubeconfig
  copy:
    src: "~/.kube-tmp/system:node:{{ ansible_fqdn }}.kubeconfig"
    dest: /etc/kubernetes/config/system:node:{{ ansible_fqdn }}.kubeconfig

- name: Copy kubelet.service unit file
  template:
    src: kubelet.service.j2
    dest: /etc/systemd/system/kubelet.service

- name: daemon-reload
  systemd: 
    daemon_reload: True

- name: Start and enable kubelet
  systemd:
    name: kubelet
    state: restarted
    enabled: True