---
- set_fact:
    cluster_hostname: "{{ cluster_hostname | default(groups['masters'][0]) }}"
    cluster_port: "{{ cluster_port | default('6443') }}"

- set_fact:
    config_path: "{{ config_path | default(lookup('env','HOME')+'/.ktrw') }}"
  delegate_to: 127.0.0.1

- set_fact:
    cluster_name: "{{ cluster_name | default(cluster_hostname.split('.')[0] | default('kubernetes')) }}"

- set_fact:
    cluster_config_path: "{{ config_path }}/{{ cluster_name }}"

- name: Download kubelet
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v1.14.0/bin/linux/amd64/kubelet
    dest: /usr/local/bin/kubelet
    mode: 0755
    owner: root
    group: root
    checksum: sha256:bcd3ae191947e55de6ee9f47ff9f68a711149d20b46ca4342aac367ded4ffc85

- name: Ensure directories exist
  file:
    state: directory
    path: "/etc/kubernetes/{{ item }}"
    mode: 0755
  with_items:
    - pki
    - config

- name: Copy certificates
  copy:
    src: "{{ item }}"
    dest: /etc/kubernetes/pki
  with_fileglob:
    - "{{ cluster_config_path }}/pki/node/system:node:{{ inventory_hostname }}*"
    - "{{ cluster_config_path }}/pki/master/ca.pem"

- name: Create kubeconfig
  template:
    src: node.kubeconfig
    dest: "/etc/kubernetes/config/system:node:{{ inventory_hostname }}.kubeconfig"
  vars:
    certificate_authority_data: "{{ lookup('file', cluster_config_path+'/pki/master/ca.pem') | b64encode }}"
    client_certificate_data: "{{ lookup('file', cluster_config_path+'/pki/node/system:node:'+inventory_hostname+'.pem') | b64encode }}"
    client_key_data: "{{ lookup('file', cluster_config_path+'/pki/node/system:node:'+inventory_hostname+'-key.pem') | b64encode }}"

- name: Create kubelet config
  template:
    src: kubelet.yml.j2
    dest: "/etc/kubernetes/config/system:node:{{ inventory_hostname }}.yml"

- name: Create systemd unit file
  template:
    src: kubelet.service.j2
    dest: /etc/systemd/system/kubelet.service

- name: daemon-reload
  systemd: 
    daemon_reload: True

- name: Start and enable kubelet
  systemd:
    name: kubelet
    state: restarted
    enabled: True