---
- name: restart kube-controller-manager
  systemd:
    name: kube-controller-manager
    state: restarted
  notify:
  - wait until kube-controller-manager is up

- name: wait until kube-controller-manager is up
  wait_for:
    port: 10257
    delay: 3