---
- set_fact:
    cluster_hostname: "{{ cluster_hostname | default(groups['masters'][0]) }}"
    
- set_fact:
    config_path: "{{ config_path | default(lookup('env','HOME')+'/.ktrw') }}"
  delegate_to: 127.0.0.1

- set_fact:
    cluster_name: "{{ cluster_name | default(cluster_hostname.split('.')[0] | default('kubernetes')) }}"

- set_fact:
    cluster_config_path: "{{ config_path }}/{{ cluster_name }}"

- name: Download etcd
  get_url:
    url: https://github.com/coreos/etcd/releases/download/v3.3.9/etcd-v3.3.9-linux-amd64.tar.gz
    dest: /tmp/etcd-v3.3.9-linux-amd64.tar.gz
    mode: 0755
    owner: root
    group: root

- name: Unarchive etcd tarball
  unarchive:
    src: /tmp/etcd-v3.3.9-linux-amd64.tar.gz
    dest: /tmp
    remote_src: True

- name: Move etcd binaries into place
  copy:
    src: "/tmp/etcd-v3.3.9-linux-amd64/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    remote_src: True
  with_items:
    - etcd
    - etcdctl

- name: Remove tmp download files
  file:
    path: "/tmp/{{ item }}"
    state: absent
  with_items:
    - etcd-v3.3.9-linux-amd64
    - etcd-v3.3.9-linux-amd64.tar.gz

- name: Make etcd binaries executable
  file:
    path: "/usr/local/bin/{{ item }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - etcd
    - etcdctl
    
- name: Ensure directories exist
  file:
    state: directory
    path: /etc/etcd/pki
    mode: 0755

- name: Copy certificates
  copy:
    src: "{{ cluster_config_path }}/pki/etcd/"
    dest: /etc/etcd/pki

- name: Create systemd unit file
  template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service

- name: daemon-reload
  systemd: 
    daemon_reload: True

- name: Start and enable etcd
  systemd:
    name: etcd
    state: restarted
    enabled: True
