---
- name: restart kube-scheduler
  systemd:
    name: kube-scheduler
    state: restarted
  notify:
  - wait until kube-scheduler is up

- name: wait until kube-scheduler is up
  wait_for:
    port: 10259
    delay: 3