- name: Download crictl
  get_url:
    url: https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.19.0/crictl-v1.19.0-linux-amd64.tar.gz
    dest: /tmp/crictl-v1.19.0-linux-amd64.tar.gz
    mode: 0755
    owner: root
    group: root
    checksum: sha256:87d8ef70b61f2fe3d8b4a48f6f712fd798c6e293ed3723c1e4bbb5052098f0ae

- name: Unarchive crictl tarball
  unarchive:
    src: /tmp/crictl-v1.19.0-linux-amd64.tar.gz
    dest: /tmp
    remote_src: True

- name: Move crictl binary into place
  copy:
    src: /tmp/crictl
    dest: /usr/local/bin/crictl
    remote_src: True

- name: Remove tmp download files
  file:
    path: /tmp/crictl
    state: absent

- name: Make crictl binaries executable
  file:
    path: /usr/local/bin/crictl
    owner: root
    group: root
    mode: 0755
