---
- set_fact:
    cluster_hostname: "{{ cluster_hostname | default(groups['masters'][0]) }}"
    cluster_port: "{{ cluster_port | default('6443') }}"

- set_fact:
    config_path: "{{ config_path | default(lookup('env','HOME')+'/.ktrw') }}"
  delegate_to: 127.0.0.1

- set_fact:
    cluster_name: "{{ cluster_name | default(cluster_hostname.split('.')[0] | default('kubernetes')) }}"

- set_fact:
    cluster_config_path: "{{ config_path }}/{{ cluster_name }}"
    
- name: Download kube-scheduler
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v1.19.8/bin/linux/amd64/kube-scheduler
    dest: /usr/local/bin/kube-scheduler
    mode: 0755
    owner: root
    group: root
    checksum: sha256:d8043890091c01ad15e461ba53d6ad3cdf0579853c70149eb3e7ee7d82582be3
  notify:
    - restart kube-scheduler

- name: Ensure directories exist
  file:
    state: directory
    path: "/etc/kubernetes/{{ item }}"
    mode: 0755
  with_items:
    - pki
    - config

- name: Copy certificates
  copy:
    src: "{{ item }}"
    dest: /etc/kubernetes/pki
  with_items:
    - "{{ cluster_config_path }}/pki/master/ca.pem"
    - "{{ cluster_config_path }}/pki/master/kube-scheduler.pem"
    - "{{ cluster_config_path }}/pki/master/kube-scheduler-key.pem"
  notify:
    - restart kube-scheduler

- name: Create kubeconfig
  template:
    src: kube-scheduler.kubeconfig
    dest: "/etc/kubernetes/config/kube-scheduler.kubeconfig"
  vars:
    certificate_authority_data: "{{ lookup('file', cluster_config_path+'/pki/master/ca.pem') | b64encode }}"
    client_certificate_data: "{{ lookup('file', cluster_config_path+'/pki/master/kube-scheduler.pem') | b64encode }}"
    client_key_data: "{{ lookup('file', cluster_config_path+'/pki/master/kube-scheduler-key.pem') | b64encode }}"
  notify:
    - restart kube-scheduler

- name: Copy scheduler config
  copy:
    src: kube-scheduler.yml
    dest: /etc/kubernetes/config/
  notify:
    - restart kube-scheduler

- name: Create systemd unit file
  template:
    src: kube-scheduler.service.j2
    dest: /etc/systemd/system/kube-scheduler.service
  notify:
    - restart kube-scheduler

- name: daemon-reload
  systemd: 
    name: kube-scheduler
    daemon_reload: True
    enabled: True
  notify:
    - restart kube-scheduler
