---
- set_fact:
    cluster_hostname: "{{ cluster_hostname | default(groups['masters'][0]) }}"

- set_fact:
    config_path: "{{ config_path | default(lookup('env','HOME')+'/.ktrw') }}"
  delegate_to: 127.0.0.1

- set_fact:
    cluster_name: "{{ cluster_name | default(cluster_hostname.split('.')[0] | default('kubernetes')) }}"

- set_fact:
    cluster_config_path: "{{ config_path }}/{{ cluster_name }}"
    
- name: Download kube-scheduler
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v1.13.1/bin/linux/amd64/kube-scheduler
    dest: /usr/local/bin/kube-scheduler
    mode: 0755
    owner: root
    group: root

- name: Ensure directories exist
  file:
    state: directory
    path: "/etc/kubernetes/{{ item }}"
    mode: 0755
  with_items:
    - pki
    - config

- name: Copy certificates
  copy:
    src: "{{ item }}"
    dest: /etc/kubernetes/pki
  with_items:
    - "{{ cluster_config_path }}/pki/master/ca.pem"
    - "{{ cluster_config_path }}/pki/master/kube-scheduler.pem"
    - "{{ cluster_config_path }}/pki/master/kube-scheduler-key.pem"

- name: Copy scheduler config
  copy:
    src: kube-scheduler.yml
    dest: /etc/kubernetes/config/

- name: Create kube-scheduler kubeconfig
  command: "kubectl config set-cluster kubernetes --certificate-authority /etc/kubernetes/pki/ca.pem --embed-certs=true --server=https://127.0.0.1:6443 --kubeconfig /etc/kubernetes/config/kube-scheduler.kubeconfig"

- name: set-credentials 
  command: "kubectl config set-credentials system:kube-scheduler --client-certificate /etc/kubernetes/pki/kube-scheduler.pem --client-key /etc/kubernetes/pki/kube-scheduler-key.pem --embed-certs=true --kubeconfig /etc/kubernetes/config/kube-scheduler.kubeconfig"

- name: set-context 
  command: "kubectl config set-context default --cluster=kubernetes --user=system:kube-scheduler --kubeconfig /etc/kubernetes/config/kube-scheduler.kubeconfig"

- name: use-context 
  command: "kubectl config use-context default --kubeconfig /etc/kubernetes/config/kube-scheduler.kubeconfig"

- name: Create systemd unit file
  template:
    src: kube-scheduler.service.j2
    dest: /etc/systemd/system/kube-scheduler.service

- name: daemon-reload
  systemd: 
    daemon_reload: True

- name: Start and enable kube-scheduler
  systemd:
    name: kube-scheduler
    state: restarted
    enabled: True