---
- set_fact:
    cluster_hostname: "{{ cluster_hostname | default(groups['masters'][0]) }}"

- set_fact:
    config_path: "{{ config_path | default(ansible_env.HOME+'/.ktrw') }}"
  delegate_to: 127.0.0.1

- set_fact:
    cluster_name: "{{ cluster_hostname.split('.')[0] | default('kubernetes') }}"

- set_fact:
    cluster_config_path: "{{ config_path }}/{{ cluster_name }}"

- name: Download kube-controller-manager
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v1.11.2/bin/linux/amd64/kube-controller-manager
    dest: /usr/local/bin/kube-controller-manager
    mode: 0755
    owner: root
    group: root

- name: Ensure directories exist
  file:
    state: directory
    path: "/etc/kubernetes/{{ item }}"
    mode: 0755
  with_items:
    - pki
    - config

- name: Copy certificates
  copy:
    src: "{{ item }}"
    dest: /etc/kubernetes/pki
  with_items:
    - "{{ cluster_config_path }}/pki/master/ca.pem"
    - "{{ cluster_config_path }}/pki/master/ca-key.pem"
    - "{{ cluster_config_path }}/pki/master/kube-controller-manager.pem"
    - "{{ cluster_config_path }}/pki/master/kube-controller-manager-key.pem"
    - "{{ cluster_config_path }}/pki/master/service-account-key.pem"

- name: Create controller-manager kubeconfig
  command: "kubectl config set-cluster kubernetes --certificate-authority {{ cluster_config_path }}/pki/master/ca.pem --embed-certs=true --server=https://127.0.0.1:6443 --kubeconfig {{ cluster_config_path }}/kube-controller-manager.kubeconfig"
  delegate_to: 127.0.0.1

- name: set-credentials 
  command: "kubectl config set-credentials system:kube-controller-manager --client-certificate {{ cluster_config_path }}/pki/master/kube-controller-manager.pem --client-key {{ cluster_config_path }}/pki/master/kube-controller-manager-key.pem --embed-certs=true --kubeconfig {{ cluster_config_path }}/kube-controller-manager.kubeconfig"
  delegate_to: 127.0.0.1

- name: set-context 
  command: "kubectl config set-context default --cluster=kubernetes --user=system:kube-controller-manager --kubeconfig {{ cluster_config_path }}/kube-controller-manager.kubeconfig"
  delegate_to: 127.0.0.1

- name: use-context 
  command: "kubectl config use-context default --kubeconfig {{ cluster_config_path }}/kube-controller-manager.kubeconfig"
  delegate_to: 127.0.0.1

- name: Copy kubeconfig
  copy:
    src: "{{ cluster_config_path }}/kube-controller-manager.kubeconfig"
    dest: /etc/kubernetes/config/kube-controller-manager.kubeconfig

- name: Create systemd unit file
  template:
    src: kube-controller-manager.service.j2
    dest: /etc/systemd/system/kube-controller-manager.service

- name: daemon-reload
  systemd: 
    daemon_reload: True

- name: Start and enable kube-controller-manager
  systemd:
    name: kube-controller-manager
    state: restarted
    enabled: True