---
- name: Ensure directories exist
  file:
    state: directory
    path: "{{ item }}"
    mode: 0755
  with_items:
    - /etc/containerd

- name: Download containerd
  unarchive:
    src: https://github.com/containerd/containerd/releases/download/v1.4.1/containerd-1.4.1-linux-amd64.tar.gz
    dest: /usr/local/
    remote_src: True
  notify:
    - restart containerd

- name: Create configuration
  template:
    src: config.toml.j2
    dest: /etc/containerd/config.toml
  notify:
    - restart containerd    

- name: Create systemd unit file
  template:
    src: containerd.service.j2
    dest: /etc/systemd/system/containerd.service
  notify:
    - restart containerd

- name: daemon-reload
  systemd: 
    name: containerd
    daemon_reload: True
    enabled: True
