---
- name: Ensure directories exist
  file:
    state: directory
    path: "{{ item }}"
    mode: 0755
  with_items:
    - /tmp/containerd
    - /etc/containerd

- name: Download containerd
  get_url:
    url: https://github.com/containerd/containerd/releases/download/v1.2.1/containerd-1.2.1.linux-amd64.tar.gz
    dest: /tmp/containerd-1.2.1.linux-amd64.tar.gz
    mode: 0755
    owner: root
    group: root
    checksum: sha256:9818e3af4f9aac8d55fc3f66114346db1d1acd48d45f88b2cefd3d3bafb380e0

- name: Unarchive tarball
  unarchive:
    src: /tmp/containerd-1.2.1.linux-amd64.tar.gz
    dest: /tmp/containerd
    remote_src: True

- name: List binaries
  find:
    paths: /tmp/containerd/bin
    file_type: file
  register: result

- name: Move binaries into place
  copy:
    src: "{{ item.path }}"
    dest: "/usr/local/bin/{{ item.path | basename }}"
    mode: 0755
    remote_src: True
  with_items: "{{ result.files }}"

- name: Remove tmp download files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/containerd-1.2.1.linux-amd64.tar.gz
    - /tmp/containerd

- name: Create configuration
  template:
    src: config.toml.j2
    dest: /etc/containerd/config.toml

- name: Create systemd unit file
  template:
    src: containerd.service.j2
    dest: /etc/systemd/system/containerd.service

- name: daemon-reload
  systemd: 
    daemon_reload: True

- name: Start and enable containerd
  systemd:
    name: containerd
    state: restarted
    enabled: True